---
- name: DNF Tasks - Upgrade all packages  # noqa 403
  dnf:
    name: '*'
    state: latest
    update_cache: true

- name: DNF Tasks - Install required packages
  dnf:
    name: "{{ dnf_packages }}"
    state: present
  when: dnf_packages is defined
